project_id = "tuoovpieeejapujaujam"

[functions.create-user]
verify_jwt = false

[functions.kick-oauth]
verify_jwt = false

[functions.event-notifications]
verify_jwt = false

[functions.admin-code]
verify_jwt = false
