project_id = "mdckorxfleckrwjmcigw"

[functions.create-user]
verify_jwt = false

[functions.kick-oauth]
verify_jwt = false

[functions.event-notifications]
verify_jwt = false

[functions.check-stream-status]
verify_jwt = false

[functions.admin-code]
verify_jwt = true

[functions.whitelabel-save]
verify_jwt = true

[functions.channel-points-sync]
verify_jwt = true

[functions.twitch-channel-points]
verify_jwt = false
